# Generated by Django 5.2.14 on 2026-05-20 20:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('application_type', models.CharField(choices=[('RECORDATION', 'Recordation'), ('RENEWAL', 'Renewal'), ('CHANGE_OF_OWNERSHIP', 'Change of Ownership'), ('CHANGE_OF_NAME', 'Change of Name'), ('DISCONTINUATION', 'Discontinuation')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('NEED_MORE_INFO', 'Need More Information'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=32)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='application_status_1508e0_idx'), models.Index(fields=['application_type'], name='application_applica_80006e_idx')],
            },
        ),
    ]
